baseurl = "/"
author = "Chester Ismay"
publishDir = "docs"
relativeurls = true
languageCode = "en-us"
title = "SOC 301 - Spring 2017"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Syllabus"
    url = "/syllabus/"  
[[menu.main]]
    name = "Problem Sets"
    url = "/problem-sets/"  
[[menu.main]]
    name = "Resources"
    url = "/resources/" 
[[menu.main]]
    name = "DataCamp"
    url = "/datacamp/" 
[[menu.main]]
    name = "Schedule"
    url = "/schedule/"      

[params]
    description = "SOC 301 - Spring 2017"
    author = "Chester Ismay"
    
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "pacific.jpg"
    width = 50
    height = 50
    alt = "Logo"

